 //------------------------------------------------------------------------------ 
 // <auto-generated> 
 // This code was generated by a tool. 
 // 
 // Changes to this file may cause incorrect behavior and will be lost if 
 // the code is regenerated. 
 // </auto-generated> 
 //------------------------------------------------------------------------------

import mongoose from "mongoose";
import { IAuthor } from "../interfaces";
import { RepositoryBase } from "./repository-base";

export interface AuthorModel extends IAuthor, mongoose.Document {
}

var modelSchema = new mongoose.Schema( { name: { type: 'String' },
  username: { type: 'String' },
  email: { type: 'String' },
  address: { type: 'String' },
  phone: { type: 'String' },
  website: { type: 'String' },
  company: { type: 'String' } } );

const Author: mongoose.Model<AuthorModel> = mongoose.model<AuthorModel>("Author", modelSchema);

export const AuthorModel = Author;

// Extends RepositoryBase
export class AuthorRepository extends RepositoryBase<AuthorModel> {
  constructor() {
    super(Author);
  }

  static getInstance(): AuthorRepository {
    return new AuthorRepository();
  }
}

// Object.seal(AuthorRepository);