 //------------------------------------------------------------------------------ 
 // <auto-generated> 
 // This code was generated by a tool. 
 // 
 // Changes to this file may cause incorrect behavior and will be lost if 
 // the code is regenerated. 
 // </auto-generated> 
 //------------------------------------------------------------------------------

import mongoose from "mongoose";
import { IComment } from "../interfaces";
import { RepositoryBase } from "./repository-base";

export interface CommentModel extends IComment, mongoose.Document {
}

var modelSchema = new mongoose.Schema( { content: { type: 'String' },
  author: { type: 'String' },
  createdAt: { type: 'Date' } } );

const Comment: mongoose.Model<CommentModel> = mongoose.model<CommentModel>("Comment", modelSchema);

export const CommentModel = Comment;

// Extends RepositoryBase
export class CommentRepository extends RepositoryBase<CommentModel> {
  constructor() {
    super(Comment);
  }

  static getInstance(): CommentRepository {
    return new CommentRepository();
  }
}

// Object.seal(CommentRepository);