 //------------------------------------------------------------------------------ 
 // <auto-generated> 
 // This code was generated by a tool. 
 // 
 // Changes to this file may cause incorrect behavior and will be lost if 
 // the code is regenerated. 
 // </auto-generated> 
 //------------------------------------------------------------------------------

import mongoose from "mongoose";
import { IPost } from "../interfaces";
import { RepositoryBase } from "./repository-base";

export interface PostModel extends IPost, mongoose.Document {
}

var modelSchema = new mongoose.Schema( { title: { type: 'String' },
  content: { type: 'String' },
  author: { type: 'String' },
  comments: { type: [ 'String' ] },
  createdAt: { type: 'Date' } } );

const Post: mongoose.Model<PostModel> = mongoose.model<PostModel>("Post", modelSchema);

export const PostModel = Post;

// Extends RepositoryBase
export class PostRepository extends RepositoryBase<PostModel> {
  constructor() {
    super(Post);
  }

  static getInstance(): PostRepository {
    return new PostRepository();
  }
}

// Object.seal(PostRepository);